sudo: required
services:
  - docker

before_install:
  - docker build -t rajatmendus/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rajatmendus/react-test npm run test

after_success:
  - docker build -t rajatmendus/multi-client ./client
  - docker build -t rajatmendus/multi-nginx ./nginx
  - docker build -t rajatmendus/multi-server ./server
  - docker build -t rajatmendus/multi-worker ./worker
  # Log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rajatmendus/multi-client
  - docker push rajatmendus/multi-nginx
  - docker push rajatmendus/multi-server
  - docker push rajatmendus/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-container-docker
    env: MultiContainerDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-348505428293
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY